server:
  port: 7000

invoicing-system:
  database: file
  database.directory: db
  database.invoices.file: INVOICES.txt
  database.companies.file: COMPANIES.txt
  database.invoice_id.file: INVOICE_ID.txt
  database.company_id.file: COMPANY_ID.txt

logging:
  level:
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG
    org:
      springframework:
        boot: INFO

spring:
  profiles:
    active: jpa
  flyway:
    enabled: false
