server:
  port: 8100

invoicing-system:
  database: memory
  database.directory: db
  database.invoices.file: INVOICES.txt
  database.companies.file: COMPANIES.txt
  database.invoice_id.file: INVOICE_ID.txt
  database.company_id.file: COMPANY_ID.txt

logging:
  level:
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG
    org:
      springframework:
        boot: INFO
