server:
  port: 7000

invoicing-system:
  database: file
  database.directory: db
  database.invoices.file: INVOICES.txt
  database.id.file: ID.txt

logging:
  level:
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG
    org:
      springframework:
        boot: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing
    username: postgres
    password: piotr
    driver-class-name: org.postgresql.Driver

flyway:
  locations: classpath:/db/migration
  database-name: invoicing
  enabled: true
