server:
  port: 7000

invoicing-system:
  allowedOrigins: http://localhost:4200
  csrf:
    disable: true


logging:
  level:
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG
    org:
      springframework:
        boot: INFO

spring:
  profiles:
    active: jpa
  flyway:
    enabled: true

  security:
    user:
      name: piotr
      password: piotr123
