spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicingsql
    username: postgres
    password: piotr
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

invoicing-system:
  database: sql