package pl.futurecollars.invoicing.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InvoiceEntry {

  @Id
  @JsonIgnore
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @ApiModelProperty(value = "ID - automatically generated by the application", required = true, example = "1")
  private int id;

  @ApiModelProperty(value = "Product/service description", required = true, example = "management software")
  private String description;

  @ApiModelProperty(value = "Quantity of product/service", required = true, example = "3")
  private int quantity;

  @ApiModelProperty(value = "Net cost of the product/service", required = true, example = "10000")
  private BigDecimal netPrice;

  @ApiModelProperty(value = "Value of tax costs", required = true, example = "2314.54")
  private BigDecimal vatValue;

  @ApiModelProperty(value = "Applicable VAT rate", required = true)
  private Vat vatRate;

  @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true)
  @JoinColumn(name = "car_related_expenses")
  @ApiModelProperty(value = "Vehicle used by the company to deliver products or services")
  private Car carRelatedExpenses;
}
