package pl.futurecollars.invoicing.model;

import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Invoice {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @ApiModelProperty(value = "ID - automatically generated by the application", required = true, example = "1")
  private int id;

  @ApiModelProperty(value = "Unique invoice number", required = true, example = "GF308455600")
  private String number;

  @ApiModelProperty(value = "Date of issue of the invoice", required = true, example = "2023-10-23")
  private LocalDate date;

  @OneToOne(cascade = CascadeType.ALL)
  @JoinColumn(name = "buyer")
  @ApiModelProperty(value = "Company purchasing the product/service", required = true)
  private Company buyer;

  @OneToOne(cascade = CascadeType.ALL)
  @JoinColumn(name = "seller")
  @ApiModelProperty(value = "Company selling the product/service", required = true)
  private Company seller;

  @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
  @JoinTable(name = "invoice_connected_to_entries", inverseJoinColumns = @JoinColumn(name = "invoice_entry_id"))
  @ApiModelProperty(value = "All invoiced products/services", required = true)
  private List<InvoiceEntry> entries;
}
