/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package pl.futurecollars.invoicing

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new App()

        when:
        def expResult = app.greeting

        then:
        expResult == "Hello World!"
    }

    def "simple test covering main class"() {
        setup:
        def app = new App()

        and:
        app.main() == "Hello World!"
    }
}
